// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJmuP87okUv8jGkGM--z4nUNe9TyQcbXU',
    appId: '1:613180327334:web:78e4981fae362de868fb67',
    messagingSenderId: '613180327334',
    projectId: 'pscexam',
    authDomain: 'pscexam.firebaseapp.com',
    storageBucket: 'pscexam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPveyhcg-SmRhDrpNvYMMaQ5J6XEUE1w',
    appId: '1:613180327334:android:e735890c325f790068fb67',
    messagingSenderId: '613180327334',
    projectId: 'pscexam',
    storageBucket: 'pscexam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dg4vQ3q4rnju5L-yA403Aoqee_-sF0I',
    appId: '1:613180327334:ios:1afa46ba1dc65be068fb67',
    messagingSenderId: '613180327334',
    projectId: 'pscexam',
    storageBucket: 'pscexam.firebasestorage.app',
    iosClientId: '613180327334-pm77bbipmndsh6tljbdfhr1gn9i7lil9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pscExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dg4vQ3q4rnju5L-yA403Aoqee_-sF0I',
    appId: '1:613180327334:ios:1afa46ba1dc65be068fb67',
    messagingSenderId: '613180327334',
    projectId: 'pscexam',
    storageBucket: 'pscexam.firebasestorage.app',
    iosClientId: '613180327334-pm77bbipmndsh6tljbdfhr1gn9i7lil9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pscExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJmuP87okUv8jGkGM--z4nUNe9TyQcbXU',
    appId: '1:613180327334:web:96e94cacf2fcc3e668fb67',
    messagingSenderId: '613180327334',
    projectId: 'pscexam',
    authDomain: 'pscexam.firebaseapp.com',
    storageBucket: 'pscexam.firebasestorage.app',
  );
}